# Generated by Django 4.0.2 on 2022-02-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='Actors',
            field=models.ManyToManyField(through='movies.Actor_Movie', to='movies.Actor'),
        ),
    ]
