# Generated by Django 4.0.2 on 2022-02-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_actor_movies_movie_actors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Actors',
            new_name='actors',
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(through='movies.Actor_Movie', to='movies.Movie'),
        ),
    ]
